gems: [jekyll-paginate]

source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
paginate:	15
paginate_path: "blog/page:num/"

collections:
  docs:
    output: true